wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1715656981
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.19
      5: 0.17.0
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
epochss:
  desc: null
  value: 2000
lrval:
  desc: null
  value: 0.01
optimizerval:
  desc: null
  value: Adam
